project_id = "jlghsevsildatnjhediw"
[functions.create-pix-payment]
enabled = true
verify_jwt = false
import_map = "./functions/create-pix-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-pix-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-pix-payment/*.html" ]

[functions.mercado-pago-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/mercado-pago-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mercado-pago-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mercado-pago-webhook/*.html" ]

[functions.ai-caster-assistant]
enabled = true
verify_jwt = false
import_map = "./functions/ai-caster-assistant/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-caster-assistant/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-caster-assistant/*.html" ]
