// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlghsevsildatnjhediw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZ2hzZXZzaWxkYXRuamhlZGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDU1MDEsImV4cCI6MjA3MTY4MTUwMX0.xhyAfuxQM8cYy_MbEV1y3PI_txRRDVlU2QhdKjubH3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});